<template>
  <div v-if="open" class="history-mask" @click.self="$emit('close')">
    <aside class="history-drawer" aria-label="生成历史管理">
      <header><div><span class="overline">GENERATED MEDIA</span><h2>生成历史管理</h2><p class="sub">浏览角色、资产、分镜图和视频版本；当前使用中的版本受保护。</p></div><button class="btn btn-sm btn-ghost" @click="$emit('close')">关闭</button></header>
      <div class="filters"><select v-model="entityType" class="input" @change="load"><option value="">全部类型</option><option value="character_portrait">标准照</option><option value="character_sheet">四视图</option><option value="character_look">造型</option><option value="asset_image">道具/场景</option><option value="asset_sheet">道具四视图</option><option value="scene">分镜图/视频</option></select><select v-model="mediaType" class="input" @change="load"><option value="">图片和视频</option><option value="image">图片</option><option value="video">视频</option></select><button class="btn btn-sm btn-secondary" :disabled="busy" @click="load">刷新</button><button class="btn btn-sm btn-danger" :disabled="busy||!selected.length" @click="bulkRemove">删除所选（{{selected.length}}）</button></div>
      <div v-if="busy" class="empty">历史加载中…</div><div v-else-if="!items.length" class="empty">暂无生成历史。</div>
      <div v-else class="media-grid"><article v-for="item in items" :key="`${item.family}-${item.id}`" class="media-card"><label class="pick"><input v-model="selected" type="checkbox" :value="`${item.family}:${item.id}`" :disabled="Boolean(item.delete_blocked_reason)">选择</label><img v-if="item.media_type==='image'" :src="item.preview_url" @click="preview=item"><video v-else :src="item.preview_url" controls preload="metadata"></video><div class="meta"><strong>{{label(item)}}</strong><span>{{item.file}}</span><span>{{new Date(item.created_at).toLocaleString()}}</span><span v-if="item.selected" class="badge badge-green">当前</span><span v-if="item.favorite" class="badge badge-orange">已收藏</span><span v-if="item.stale" class="badge badge-gray">已过期</span><small v-if="item.delete_blocked_reason" class="warn-msg">{{item.delete_blocked_reason}}</small></div><div class="actions"><button class="btn btn-sm btn-secondary" :disabled="busy||item.selected||item.stale" @click="selectCurrent(item)">设为当前最佳</button><button v-if="item.family==='asset_variant'" class="btn btn-sm btn-ghost" :disabled="busy" @click="favorite(item)">{{item.favorite?'取消收藏':'收藏保留'}}</button><button class="btn btn-sm btn-danger" :disabled="busy||Boolean(item.delete_blocked_reason)" @click="remove(item)">删除历史及无引用文件</button></div></article></div>
    </aside>
    <div v-if="preview" class="preview-mask" @click="preview=null"><img :src="preview.preview_url"></div>
  </div>
</template>
<script setup>
import { ref, watch } from 'vue'
import { api } from '../api'
import { useToastStore } from '../stores/toast'
const props=defineProps({open:Boolean,projectId:{type:[String,Number],required:true}}), emit=defineEmits(['close','changed'])
const toast=useToastStore(),items=ref([]),selected=ref([]),busy=ref(false),entityType=ref(''),mediaType=ref(''),preview=ref(null)
const labels={character_portrait:'角色标准照',character_sheet:'角色四视图',character_look:'角色造型',asset_image:'道具/场景图',asset_sheet:'道具四视图',scene:'Scene'}
function label(item){return `${labels[item.entity_type]||item.entity_type} · ${item.media_type==='video'?'视频':'图片'}`}
async function load(){busy.value=true;try{const{data}=await api.generatedMedia(props.projectId,{entity_type:entityType.value,media_type:mediaType.value});items.value=data.items||[];selected.value=[]}catch(e){toast.error(e.response?.data?.error||'加载生成历史失败')}finally{busy.value=false}}
async function selectCurrent(item){busy.value=true;try{await api.selectGeneratedMedia(props.projectId,item.family,item.id);await load();emit('changed');toast.success('已设为当前最佳版本')}catch(e){toast.error(e.response?.data?.error||'选择版本失败')}finally{busy.value=false}}
async function favorite(item){busy.value=true;try{await api.favoriteGeneratedMedia(props.projectId,item.family,item.id,!item.favorite);await load();toast.success(item.favorite?'已取消收藏':'已收藏保留')}catch(e){toast.error(e.response?.data?.error||'收藏失败')}finally{busy.value=false}}
async function remove(item){if(!confirm(`确定删除 ${item.file} 的历史记录？仅在没有其他引用时才会同时删除硬盘文件。`))return;busy.value=true;try{await api.deleteGeneratedMedia(props.projectId,item.family,item.id);await load();emit('changed');toast.success('历史记录已删除')}catch(e){toast.error(e.response?.data?.error||'删除失败')}finally{busy.value=false}}
async function bulkRemove(){if(!confirm(`确定删除所选 ${selected.value.length} 个历史版本？`))return;const rows=selected.value.map(value=>{const[family,id]=value.split(':');return{family,id:Number(id)}});busy.value=true;try{await api.bulkDeleteGeneratedMedia(props.projectId,rows);await load();emit('changed');toast.success('所选历史已删除')}catch(e){toast.error(e.response?.data?.error||'批量删除失败')}finally{busy.value=false}}
watch(()=>props.open,value=>{if(value)load()})
</script>
<style scoped>
.history-mask{position:fixed;inset:0;z-index:110;background:#0008;display:flex;justify-content:flex-end}.history-drawer{width:min(920px,96vw);height:100%;overflow:auto;background:var(--bg);padding:22px;box-shadow:-10px 0 35px #0005}.history-drawer header,.filters{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.filters{justify-content:flex-start;margin:18px 0}.filters .input{width:auto}.media-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:14px}.media-card{display:grid;gap:9px;padding:12px;border:1px solid var(--border);border-radius:12px;background:var(--card)}.media-card img,.media-card video{width:100%;height:180px;object-fit:contain;background:#000;border-radius:8px}.pick{font-size:12px}.meta{display:grid;gap:4px;font-size:12px;word-break:break-all}.preview-mask{position:fixed;inset:0;z-index:120;background:#000d;display:grid;place-items:center}.preview-mask img{max-width:94vw;max-height:94vh}@media(max-width:600px){.history-drawer{width:100vw}.media-grid{grid-template-columns:1fr}}
</style>
