<template>
  <section class="section director">
    <div class="section-head">
      <div><span class="overline">AI DIRECTOR</span><h2>AI导演方案</h2><p class="sub">输入场景概况，AI先完成镜头设计；你只需审核和修改。</p></div>
    </div>
    <div class="card ai-director-card">
      <label>场景概况<textarea v-model="directorBrief" class="textarea" rows="4" placeholder="默认使用Scene剧情；可补充你希望这段怎么拍" /></label>
      <label>补充要求（可选）<textarea v-model="directorRequirements" class="textarea" rows="2" placeholder="例如：情绪克制、保留原对白、不要远景、禁止旁白" /></label>
      <button class="btn" :disabled="generatingDirector || !directorBrief.trim()" @click="generateDirectorDraft">{{ generatingDirector ? 'AI导演中…' : 'AI生成完整导演方案' }}</button>
    </div>
    <div v-if="directorDraft" class="card director-draft"><div class="section-head"><div><strong>AI导演草稿 · {{ directorDraft.shots.length }}镜</strong><p class="sub">尚未保存，确认后才替换当前Shot设计。</p></div><div class="section-actions"><button class="btn btn-sm btn-ghost" @click="directorDraft=null">放弃</button><button class="btn btn-sm" :disabled="saving" @click="confirmDirectorDraft">确认导入并保存</button></div></div><div v-for="(s,i) in directorDraft.shots" :key="i" class="draft-shot"><strong>{{ i+1 }}. {{ s.description }}</strong><span>{{ s.shot_type }} · {{ s.camera_angle }} · {{ s.camera_movement }} · {{ s.duration }}秒</span><p>{{ s.start_state }} → {{ s.end_state }}</p><details><summary>导演细节与自动检查</summary><p>主体：{{ s.prompt_subject }}</p><p>动作：{{ s.prompt_action }}</p><p>摄影机：{{ s.prompt_camera }}</p><p>光线：{{ s.prompt_lighting }}</p><p>风格：{{ s.prompt_style }}</p><ul><li v-for="check in s.checks" :key="check">{{ check }}</li></ul></details></div></div>
    <details class="card advanced-editor"><summary><strong>高级：逐镜手工编辑</strong>（已有 {{ shots.length }} 镜）</summary><div class="section-actions advanced-actions"><button class="btn btn-sm btn-secondary" @click="createFiveActSkeleton">创建五幕骨架</button><button class="btn btn-sm btn-secondary" @click="addShot">＋ 镜头</button><button class="btn btn-sm" :disabled="saving" @click="saveAll">{{ saving ? '保存中…' : '保存导演设计' }}</button></div>
    <div v-if="loading" class="card empty">加载镜头…</div>
    <div v-else-if="!shots.length" class="card empty">暂无镜头。点击“＋ 镜头”开始导演设计。</div>
    <div v-for="(shot, index) in shots" :key="shot._key" class="card shot-card">
      <div class="shot-head"><strong>镜头 {{ index + 1 }} · {{ actLabel(shot.act_type) }}</strong><button class="btn btn-sm btn-danger" @click="removeShot(index)">删除</button></div>
      <div class="shot-grid five">
        <label>叙事幕<select v-model="shot.act_type" class="input"><option v-for="act in acts" :key="act.value" :value="act.value">{{ act.label }}</option></select></label>
        <label>景别<input v-model="shot.shot_type" class="input" placeholder="全景 / 中景 / 近景 / 特写" /></label>
        <label>机位角度<input v-model="shot.camera_angle" class="input" placeholder="平视 / 俯拍 / 仰拍" /></label>
        <label>运镜<input v-model="shot.camera_movement" class="input" placeholder="固定 / 推 / 拉 / 摇 / 跟" /></label>
        <label>时长（秒）<input v-model.number="shot.duration" class="input" type="number" min="0.1" max="120" step="0.1" /></label>
      </div>
      <div class="shot-grid two"><label>转场<select v-model="shot.transition_type" class="input"><option value="">无</option><option value="cut">硬切</option><option value="dissolve">叠化</option><option value="fade">淡入淡出</option><option value="wipe">划像</option><option value="match_cut">匹配剪辑</option></select></label><label>转场说明<input v-model="shot.transition_note" class="input" placeholder="可选，只描述与下一镜的衔接意图" /></label></div>
      <div class="shot-grid two"><label>起始状态<input v-model="shot.start_state" class="input" placeholder="可选，用于起止状态Skill草稿" /></label><label>结束状态<input v-model="shot.end_state" class="input" placeholder="可选，用于下一镜连续性" /></label></div>
      <details v-if="shot.id" class="shot-assets"><summary>镜头造型覆盖</summary><p class="sub">不选择时继承场景；每个角色可选一个套装，并可附加独立造型资产。</p><div v-for="character in characters" :key="character.id" class="asset-character"><strong>{{ character.name }}</strong><select v-model="shot._outfits[character.id]" class="input"><option value="">继承场景套装</option><option v-for="o in outfits[character.id] || []" :key="o.id" :value="o.id">{{ o.name }} · {{ o.audit_status }}</option></select><div class="look-options"><label v-for="look in looks[character.id] || []" :key="look.id"><input v-model="shot._looks" type="checkbox" :value="look.id"> {{ look.name }} <small>{{ look.category }}</small></label></div></div><button class="btn btn-sm btn-secondary" :disabled="shot._assetBusy" @click="saveShotAssets(shot)">{{ shot._assetBusy ? '保存中…' : '保存镜头造型' }}</button></details>
      <label><span class="field-label-actions">简单镜头说明 <button class="btn btn-sm btn-secondary" :disabled="shot._busy || !shot.description.trim()" @click="expandShot(shot)">{{ shot._busy ? 'AI 扩写中…' : 'AI 扩写镜头' }}</button></span><textarea v-model="shot.description" class="textarea" rows="2" placeholder="例如：女主拔剑挡在男主身前" /></label>
      <div class="shot-grid two"><label>对白<textarea v-model="shot.dialogue" class="textarea" rows="2" /></label><label>情绪<textarea v-model="shot.emotion" class="textarea" rows="2" /></label></div>
      <details open><summary>五段导演提示词</summary>
        <div class="prompt-grid">
          <label><span>1 主体与五官</span><textarea v-model="shot.prompt_subject" class="textarea" rows="2" /></label>
          <label><span>2 姿态与动作</span><textarea v-model="shot.prompt_action" class="textarea" rows="2" /></label>
          <label><span>3 摄影机与构图</span><textarea v-model="shot.prompt_camera" class="textarea" rows="2" /></label>
          <label><span>4 光线与氛围</span><textarea v-model="shot.prompt_lighting" class="textarea" rows="2" /></label>
          <label><span>5 视觉风格与质感</span><textarea v-model="shot.prompt_style" class="textarea" rows="2" /></label>
        </div>
        <div class="workbench">
          <div class="prompt-preview">{{ assembledPrompt(shot) || '填写五段内容后可优化、翻译并应用风格' }}</div>
          <div class="tool-row">
            <select v-model="shot._preset" class="input preset-select"><option value="">选择风格预设</option><option v-for="p in (shot._presets || presets)" :key="p.id" :value="p.id">{{ p.name }} · {{ p._match_reason || p.reason }}</option></select>
            <button class="btn btn-sm btn-secondary" :disabled="!shot._preset" @click="applyStyle(shot)">应用风格</button>
            <button class="btn btn-sm btn-secondary" :disabled="shot._busy || !shot.id" @click="buildFivePartPrompt(shot)">构建五段</button>
            <button class="btn btn-sm btn-secondary" :disabled="shot._busy || !shot.id" @click="buildStatePrompt(shot)">起止状态草稿</button>
            <button class="btn btn-sm btn-secondary" :disabled="shot._busy || !assembledPrompt(shot)" @click="runPromptAction(shot, 'optimize')">AI 优化</button>
            <button class="btn btn-sm btn-secondary" :disabled="shot._busy || !assembledPrompt(shot)" @click="runPromptAction(shot, 'translate')">翻译英文</button>
            <button class="btn btn-sm btn-ghost" :disabled="!shot.id" @click="loadHistory(shot)">历史版本</button>
          </div>
          <div v-if="shot._stateDraft" class="workbench"><pre class="prompt-preview">{{ JSON.stringify(shot._stateDraft, null, 2) }}</pre><button class="btn btn-sm" @click="applyStateDraft(shot)">应用到本镜五段（仍需保存）</button></div>
          <label>负向提示词<textarea v-model="shot.negative_prompt" class="textarea" rows="2" placeholder="需要排除的画面内容，保存后进入场景生成约束" /></label>
          <div v-if="shot._history?.length" class="history"><button v-for="v in shot._history" :key="v.id" class="history-item" :disabled="shot._busy" @click="rollbackVersion(shot, v)">{{ promptHistoryLabel(v) }} · {{ new Date(v.created_at).toLocaleString() }}</button></div>
        </div>
      </details>
    </div>
    </details>
  </section>
</template>
<script setup>
import { ref, watch, onBeforeUnmount } from 'vue'
import { api } from '../api'
import { useToastStore } from '../stores/toast'
import { promptHistoryLabel } from '../utils/directorWorkflow.js'
import { createDraftSafety } from '../utils/draftSafety.js'
const emit = defineEmits(['scene-changed'])
const props = defineProps({ projectId: { type: [String, Number], required: true }, sceneId: { type: [String, Number], required: true }, genre: { type: String, default: '' }, tone: { type: String, default: '' }, sceneTitle: { type: String, default: '' }, sceneContent: { type: String, default: '' } })
const toast = useToastStore(); const shots = ref([]); const presets = ref([]); const characters = ref([]); const looks = ref({}); const outfits = ref({}); const loading = ref(false); const saving = ref(false); const generatingDirector = ref(false); const directorBrief = ref(''); const directorRequirements = ref(''); const directorDraft = ref(null); let key = 0; let draftSafety
const draftValue = () => ({ directorBrief: directorBrief.value, directorRequirements: directorRequirements.value, shots: shots.value })
function applyLocalDraft(draft) { directorBrief.value = draft.directorBrief || ''; directorRequirements.value = draft.directorRequirements || ''; if (Array.isArray(draft.shots)) shots.value = draft.shots }
function startDraftSafety() { draftSafety?.dispose(); draftSafety = createDraftSafety({ key: `draft:shot-director:${props.projectId}:${props.sceneId}`, getDraft: draftValue, applyDraft: applyLocalDraft, save: saveAll }); draftSafety.start() }
const acts = [{ value: 'setup', label: '建置' }, { value: 'rising', label: '发展' }, { value: 'midpoint', label: '转折' }, { value: 'falling', label: '回落' }, { value: 'resolution', label: '收束' }]
const actLabel = value => acts.find(a => a.value === value)?.label || '建置'
const blank = (actType = 'setup') => ({ _key: `new-${++key}`, _preset: '', _history: [], start_state: '', end_state: '', _stateDraft: '', act_type: actType, shot_type: '中景', camera_angle: '平视', camera_movement: '固定', transition_type: '', transition_note: '', duration: 2, description: '', dialogue: '', emotion: '', prompt_subject: '', prompt_action: '', prompt_camera: '', prompt_lighting: '', prompt_style: '', negative_prompt: '' })
const hydrate = s => ({ ...s, _key: `shot-${s.id}`, _preset: '', _history: [], _presets: [], _looks: [], _outfits: {}, _assetBusy: false, start_state: s.start_state || '', end_state: s.end_state || '', _stateDraft: '' })
function assembledPrompt(s) { return [s.prompt_subject, s.prompt_action, s.prompt_camera, s.prompt_lighting, s.prompt_style].map(v => (v || '').trim()).filter(Boolean).join(', ') }
function setPrompt(shot, text) { const lines = String(text || '').split(/\r?\n/).map(v => v.trim()); if (lines.length === 5) { [shot.prompt_subject, shot.prompt_action, shot.prompt_camera, shot.prompt_lighting, shot.prompt_style] = lines; return } const parts = String(text || '').split(/\n|；|;/).map(v => v.trim()).filter(Boolean); if (parts.length >= 5) [shot.prompt_subject, shot.prompt_action, shot.prompt_camera, shot.prompt_lighting, shot.prompt_style] = [parts[0], parts[1], parts[2], parts[3], parts.slice(4).join(', ')]; else shot.prompt_style = text }
async function generateDirectorDraft() { generatingDirector.value = true; try { const { data } = await api.sceneDirectorDraft(props.projectId, props.sceneId, { brief: directorBrief.value, requirements: directorRequirements.value }); directorDraft.value = data.draft; toast.success('完整导演草稿已生成，请审核后确认') } catch (e) { toast.error(e.response?.data?.error || 'AI导演方案生成失败') } finally { generatingDirector.value = false } }
async function confirmDirectorDraft() { if (!directorDraft.value?.shots?.length) return; if (shots.value.length && !window.confirm('确认后将替换当前Shot导演设计；Scene剧情和起始帧提示词不会被覆盖。是否继续？')) return; saving.value = true; try { const payload = directorDraft.value.shots.map(({ checks, ...shot }) => shot); const { data } = await api.replaceSceneShots(props.projectId, props.sceneId, payload); shots.value = data.shots.map(hydrate); directorDraft.value = null; emit('scene-changed'); toast.success('AI导演方案已保存，可继续手工微调或生成分镜图') } catch (e) { toast.error(e.response?.data?.error || '保存AI导演方案失败') } finally { saving.value = false } }
async function load() { directorBrief.value = props.sceneContent || directorBrief.value; directorDraft.value = null; loading.value = true; try { const [{ data }, presetRes, characterRes] = await Promise.all([api.sceneShots(props.projectId, props.sceneId), api.presetRecommendations({ genre: props.genre, tone: props.tone, scene_type: props.sceneTitle, tags: props.sceneContent, limit: 5 }), api.characters(props.projectId)]); shots.value = (data.shots || []).map(hydrate); presets.value = (presetRes.data || []).map(r => ({ ...r.preset, _match_reason: (r.reasons || []).join('；'), _score: r.score })); characters.value = characterRes.data || []; await Promise.all(characters.value.map(async c => { const [l, o] = await Promise.all([api.characterLooks(props.projectId, c.id), api.characterOutfits(props.projectId, c.id)]); looks.value[c.id] = (l.data || []).filter(v => ['approved', 'published'].includes(v.audit_status)); outfits.value[c.id] = (o.data || []).filter(v => ['approved', 'published'].includes(v.audit_status)) })); await Promise.all(shots.value.filter(s => s.id).map(async shot => { const [recs, shotLooks, shotOutfits] = await Promise.all([api.shotStyleRecommendations(props.projectId, shot.id, 3), api.shotLooks(props.projectId, shot.id), api.shotOutfits(props.projectId, shot.id)]); shot._presets = (recs.data || []).map(r => ({ ...r.preset, _match_reason: (r.reasons || []).join('；'), _score: r.score })); shot._looks = (shotLooks.data || []).map(v => v.look_id); shot._outfits = Object.fromEntries((shotOutfits.data || []).map(v => [v.character_id, v.outfit_id])) })); startDraftSafety() } catch (e) { toast.error(e.response?.data?.error || '加载镜头失败') } finally { loading.value = false } }
async function saveShotAssets(shot) { shot._assetBusy = true; try { const lookRows = shot._looks.map((lookId, order) => ({ look_id: Number(lookId), order, is_featured: order === 0 })); const outfitRows = Object.entries(shot._outfits).filter(([, outfitId]) => outfitId).map(([characterId, outfitId]) => ({ character_id: Number(characterId), outfit_id: Number(outfitId) })); await Promise.all([api.updateShotLooks(props.projectId, shot.id, lookRows), api.updateShotOutfits(props.projectId, shot.id, outfitRows)]); emit('scene-changed'); toast.success('镜头造型已保存') } catch (e) { toast.error(e.response?.data?.error || '保存镜头造型失败') } finally { shot._assetBusy = false } }
function addShot() { shots.value.push(blank(shots.value.at(-1)?.act_type || 'setup')) }
function createFiveActSkeleton() { if (shots.value.length && !window.confirm('创建五幕骨架会替换当前尚未保存的镜头，是否继续？')) return; shots.value = acts.map((act, index) => ({ ...blank(act.value), shot_type: index === 0 ? '全景' : index === 2 ? '特写' : '中景', description: `${act.label}：`, duration: 2 })) }
function removeShot(index) { shots.value.splice(index, 1) }
async function saveAll() { saving.value = true; try { const payload = shots.value.map(({ _key, _preset, _presets, _history, _busy, _stateDraft, _looks, _outfits, _assetBusy, scene_id, created_at, updated_at, order, ...s }) => s); const { data } = await api.replaceSceneShots(props.projectId, props.sceneId, payload); shots.value = data.shots.map(hydrate); draftSafety?.markSaved(); emit('scene-changed'); toast.success('导演镜头已保存，场景事实保持不变，旧生成结果已失效') } catch (e) { toast.error(e.response?.data?.error || '保存镜头失败'); throw e } finally { saving.value = false } }
async function applyStyle(shot) { try { if (!shot.id) { toast.error('请先保存镜头'); return } const preview = await api.applyShotStylePreset(props.projectId, shot.id, shot._preset, true); const p = preview.data.preset; if (!window.confirm(`将追加：${p.prompt_tail || '无'}\n负向词：${p.negative_tail || '无'}\n原因：${p.reason || preview.data.metadata?.preset_name || ''}\n是否应用？`)) return; const { data } = await api.applyShotStylePreset(props.projectId, shot.id, shot._preset, false); shot.prompt_style = data.prompt_style; shot.negative_prompt = data.negative_prompt || ''; await loadHistory(shot); emit('scene-changed'); toast.success(data.changed ? '已应用风格预设并记录来源' : '该预设已应用，无需重复追加') } catch (e) { toast.error(e.response?.data?.error || '应用预设失败') } }
async function buildStatePrompt(shot) { shot._busy = true; try { const { data } = await api.shotStatePromptDraft(props.projectId, shot.id, { start_state: shot.start_state, end_state: shot.end_state }); shot._stateDraft = data.draft; toast.success('已生成起止状态草稿（未自动保存）') } catch (e) { toast.error(e.response?.data?.error || '生成起止状态草稿失败') } finally { shot._busy = false } }
function applyStateDraft(shot) { const d = shot._stateDraft; if (!d) return; [shot.prompt_subject, shot.prompt_action, shot.prompt_camera, shot.prompt_lighting, shot.prompt_style] = [d.subject, d.action, d.camera, d.lighting, d.style]; toast.success('草稿已填入五段，请检查后保存') }
async function buildFivePartPrompt(shot) { shot._busy = true; try { const template = '{{subject}}\n{{action}}\n{{camera}}\n{{lighting}}\n{{style}}'; const { data } = await api.buildPrompt({ project_id: Number(props.projectId), entity_type: 'shot', entity_id: shot.id, template, params: { subject: shot.prompt_subject || '', action: shot.prompt_action || '', camera: shot.prompt_camera || '', lighting: shot.prompt_lighting || '', style: shot.prompt_style || '' } }); setPrompt(shot, data.prompt); await loadHistory(shot); toast.success('已按五段结构构建提示词') } catch (e) { toast.error(e.response?.data?.error || '构建提示词失败') } finally { shot._busy = false } }
async function expandShot(shot) { shot._busy = true; try { if (shot.id) { const { data } = await api.expandShotDirectorPrompt(props.projectId, shot.id, { description: shot.description, asset_context: `${props.sceneTitle}；${props.sceneContent}`, start_state: shot.start_state || '', end_state: shot.end_state || '', }); [shot.prompt_subject, shot.prompt_action, shot.prompt_camera, shot.prompt_lighting, shot.prompt_style] = [data.subject, data.action, data.camera, data.lighting, data.style]; } else { const { data } = await api.optimizePrompt({ project_id: Number(props.projectId), entity_type: 'shot', entity_id: 0, prompt: `请依据简单说明扩写单个分镜：${shot.description}`, context: `叙事幕：${actLabel(shot.act_type)}；必须严格输出五行，依次为主体与五官；姿态与动作；摄影机与构图；光线与氛围；视觉风格与质感。每行只写对应内容，不要编号、标题或解释。` }); const parts = data.prompt.split(/\n|；|;/).map(v => v.replace(/^\s*\d+[.、:)：-]?\s*/, '').trim()).filter(Boolean); if (parts.length < 5) throw new Error('AI 未按五段结构返回，请重试'); [shot.prompt_subject, shot.prompt_action, shot.prompt_camera, shot.prompt_lighting, shot.prompt_style] = [parts[0], parts[1], parts[2], parts[3], parts.slice(4).join(', ')]; } toast.success('镜头五段提示词已扩写') } catch (e) { toast.error(e.response?.data?.error || e.message || '镜头扩写失败') } finally { shot._busy = false } }
async function runPromptAction(shot, action) { if (!shot.id) { toast.error('请先保存镜头'); return } shot._busy = true; try { const payload = { project_id: Number(props.projectId), entity_type: 'shot', entity_id: shot.id, prompt: assembledPrompt(shot), context: `${shot.description}；情绪：${shot.emotion}` }; const { data } = action === 'optimize' ? await api.optimizePrompt(payload) : await api.translatePrompt({ ...payload, target_lang: 'en' }); setPrompt(shot, data.prompt); await loadHistory(shot); toast.success(action === 'optimize' ? '提示词已优化' : '提示词已翻译') } catch (e) { toast.error(e.response?.data?.error || '提示词处理失败') } finally { shot._busy = false } }
async function loadHistory(shot) { try { const { data } = await api.promptHistory({ project_id: props.projectId, entity_type: 'shot', entity_id: shot.id, limit: 10 }); shot._history = data || [] } catch (e) { toast.error(e.response?.data?.error || '加载历史失败') } }
async function rollbackVersion(shot, version) { shot._busy = true; try { const { data } = await api.rollbackPrompt({ project_id: Number(props.projectId), entity_type: 'shot', entity_id: shot.id, version_id: version.id }); setPrompt(shot, data.prompt); await loadHistory(shot); toast.success('已回滚到该历史版本，保存镜头后应用到场景') } catch (e) { toast.error(e.response?.data?.error || '回滚失败') } finally { shot._busy = false } }
watch(() => props.sceneId, load, { immediate: true })
watch(draftValue, () => draftSafety?.schedule(), { deep: true })
onBeforeUnmount(() => draftSafety?.dispose())
</script>
<style scoped>
.director{grid-column:1/-1}.ai-director-card{display:grid;gap:12px;padding:18px;margin-bottom:14px}.ai-director-card label{display:grid;gap:6px}.director-draft{padding:18px;margin-bottom:14px}.draft-shot{display:grid;gap:5px;padding:12px 0;border-top:1px solid var(--border)}.draft-shot span,.draft-shot p{color:var(--text-secondary);margin:0}.advanced-editor{padding:18px}.advanced-actions{margin:12px 0}.shot-card{padding:18px;margin-bottom:14px}.shot-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.shot-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.shot-grid.five{grid-template-columns:repeat(5,minmax(0,1fr))}.shot-grid.two{grid-template-columns:1fr 1fr}.shot-card label{display:grid;gap:6px;color:var(--text-secondary);font-size:12px;margin-bottom:12px}summary{cursor:pointer;font-weight:600;margin:4px 0 12px}.prompt-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px}.empty{padding:24px;color:var(--text-secondary)}.workbench{border-top:1px solid var(--border);padding-top:12px}.prompt-preview{padding:12px;border-radius:8px;background:var(--surface-secondary);font-size:13px;line-height:1.6}.tool-row{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.preset-select{min-width:260px;flex:1}.shot-assets{border:1px solid var(--border);border-radius:10px;padding:10px;margin-bottom:12px}.asset-character{display:grid;grid-template-columns:120px minmax(180px,1fr) 2fr;gap:10px;align-items:start;padding:8px 0;border-top:1px solid var(--border)}.look-options{display:flex;gap:8px;flex-wrap:wrap}.look-options label{display:flex;margin:0}.negative{margin-top:8px;color:var(--text-secondary);font-size:12px}.history{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.history-item{border:1px solid var(--border);background:transparent;color:var(--text-secondary);border-radius:6px;padding:5px 8px;cursor:pointer;font-size:11px}@media(max-width:900px){.shot-grid,.prompt-grid{grid-template-columns:1fr 1fr}}@media(max-width:560px){.shot-grid,.shot-grid.two,.prompt-grid{grid-template-columns:1fr}}
</style>
