<template>
  <div class="page fade-up">
    <router-link :to="`/projects/${pid}`" class="back">← 返回项目</router-link>
    <div class="head"><div><h1>{{character?.name || '角色'}} · 新形象与服装</h1><p class="sub">所有新形象都绑定当前角色，并以该角色标准像锁定身份后换装；不会创建无归属套装。</p></div><div class="head-actions"><button class="btn" :disabled="!character?.portrait" @click="openDesign">✨ 基于标准像设计新形象</button><button v-if="mode!=='motion'" class="btn btn-secondary" @click="mode==='assets'?openLook():openOutfit()">＋ {{mode==='assets'?'手工新建单件资产':'手工组合套装'}}</button></div></div>
    <div class="card character-anchor"><img v-if="character?.portrait" :src="img(character.portrait)" alt="角色标准像"><div v-else class="anchor-empty">暂无标准像</div><div><strong>身份锚点：{{character?.name || '加载中…'}}</strong><span v-if="character?.portrait">生成新形象时，Picture 1 固定使用这张标准像，锁定同一张脸和项目画风。</span><span v-else class="error-text">请先返回项目，为该角色生成或上传标准像；没有标准像不能提交换装设计。</span></div></div>
    <div class="card workflow-tip"><strong>推荐流程</strong><span>① 独立资产中新建服装/鞋履/发型/配饰并审核、生成参考图</span><span>② 完整套装中组合这些资产并审核</span><span>③ 生成套装图和四视图</span><span>④ 在场景编辑的“本场角色造型套装”中选择使用</span></div>
    <div class="mode-tabs"><button class="btn btn-sm" :class="mode==='outfits'?'':'btn-ghost'" @click="mode='outfits'">完整套装（{{outfits.length}}）</button><button class="btn btn-sm" :class="mode==='assets'?'':'btn-ghost'" @click="mode='assets'">独立资产（{{looks.length}}）</button><button class="btn btn-sm" :class="mode==='motion'?'':'btn-ghost'" @click="mode='motion'">动态参考（{{motions.length}}）</button></div>
    <div v-if="error" class="notice error-notice">{{error}}</div>

    <template v-if="mode==='assets'">
      <div class="category-tabs"><button v-for="(v,k) in labels" :key="k" class="btn btn-sm" :class="activeCategory===k?'':'btn-ghost'" @click="activeCategory=k">{{v}}（{{looks.filter(x=>x.category===k).length}}）</button></div>
      <div class="look-grid"><article v-for="x in filteredLooks" :key="x.id" class="card look">
        <img v-if="x.image" :src="img(x.image)"><div v-else class="empty-img">{{x.image_task_id?'H3 生成中…':'暂无参考图'}}</div>
        <header><h3>{{x.name}}</h3><span class="badge">{{labels[x.category]||x.category}}</span></header><p>{{x.description||'暂无描述'}}</p>
        <small>{{x.audit_status}} · 优先级 {{x.priority}}</small><p v-if="x.image_error" class="error-text">{{x.image_error}}</p>
        <div class="actions"><button class="btn btn-sm btn-ghost" @click="openLook(x)">编辑</button><button class="btn btn-sm btn-secondary" @click="derive(x)">以此新建</button><button class="btn btn-sm btn-ghost" @click="actLook(x,'expand')">AI扩写</button><button class="btn btn-sm btn-secondary" @click="actLook(x,'approve')">审核通过</button><button class="btn btn-sm" :disabled="x.image_task_id || (x.audit_status!=='approved'&&x.audit_status!=='published')" @click="actLook(x,'image')">{{x.image_task_id?'生成中…':'生成参考图'}}</button><label class="btn btn-sm btn-ghost">上传图<input hidden type="file" accept="image/*" @change="upload(x,$event)"></label><button class="btn btn-sm btn-danger" @click="removeLook(x)">删除</button></div>
      </article></div>
    </template>

    <div v-else-if="mode==='outfits'" class="outfit-grid"><article v-for="o in outfits" :key="o.id" class="card outfit">
      <div class="outfit-binding"><img v-if="character?.portrait" :src="img(character.portrait)"><span>绑定角色：<strong>{{character?.name}}</strong><br>身份参考：当前角色标准像（Picture 1）</span></div><div class="outfit-media"><img v-if="o.image" :src="img(o.image)"><div v-else class="empty-img">{{o.image_task_id?'H3 生成换装定妆照中…':'待生成换装定妆照'}}</div><img v-if="o.sheet" :src="img(o.sheet)"><div v-else class="empty-img">{{o.sheet_task_id?'H3 生成四视图中…':'暂无四视图'}}</div></div>
      <header><h3>{{o.name}}</h3><span class="badge">{{o.audit_status}}</span></header><p>{{o.description||'暂无套装说明'}}</p>
      <div class="chips"><span v-for="i in o.items" :key="i.id" class="chip">{{labels[i.look?.category]}} · {{i.look?.name}}</span></div>
      <p v-if="o.image_error||o.sheet_error" class="error-text">{{o.image_error||o.sheet_error}}</p>
      <div class="actions"><button class="btn btn-sm btn-ghost" @click="openOutfit(o)">编辑组合</button><button class="btn btn-sm btn-secondary" @click="outfitAct(o,'approve')">审核通过</button><button class="btn btn-sm" :disabled="o.image_task_id||!approved(o)||!character?.portrait" @click="outfitAct(o,'image')">{{o.image_task_id?'生成中…':'用标准像生成换装图'}}</button><label class="btn btn-sm btn-ghost">手工替换换装图<input hidden type="file" accept="image/*" @change="uploadOutfit(o,$event,false)"></label><button class="btn btn-sm" :disabled="o.sheet_task_id||!o.image||!approved(o)" @click="outfitAct(o,'sheet')">{{o.sheet_task_id?'生成中…':'生成四视图'}}</button><label class="btn btn-sm btn-ghost">上传四视图<input hidden type="file" accept="image/*" @change="uploadOutfit(o,$event,true)"></label><button class="btn btn-sm btn-danger" @click="removeOutfit(o)">删除</button></div>
    </article></div>

    <section v-else class="card motion-panel"><h2>角色动态参考视频</h2><p class="sub">用于保存可复用的走路、转身、表情或口型参考；不会自动占用H3静态参考图名额。</p><form class="motion-upload" @submit.prevent="uploadMotion"><label>名称<input v-model="motionName" class="input" placeholder="例如：自然走路节奏"></label><label>视频<input ref="motionVideo" type="file" accept="video/mp4,video/webm,video/quicktime" required></label><label>可选音频<input ref="motionAudio" type="file" accept="audio/*"></label><button class="btn" :disabled="motionUploading">{{motionUploading?'上传中…':'上传动态参考'}}</button></form><article v-for="m in motions" :key="m.id" class="motion-row"><video :src="fileURL(m.video_path)" controls preload="metadata"></video><div><strong>{{m.name}}</strong><p>{{m.selected?'当前选中':'可用参考'}}<span v-if="m.audio_path"> · 含音频</span></p></div><button class="btn btn-sm btn-secondary" :disabled="m.selected" @click="selectMotion(m)">设为当前</button><button class="btn btn-sm btn-danger" @click="deleteMotion(m)">删除</button></article></section>

    <div v-if="designing" class="modal-mask" @click.self="designing=false"><form class="modal card design-modal" @submit.prevent="designOutfit"><h2>基于角色标准像设计新形象</h2><p class="sub">角色标准像负责锁定同一张脸和项目画风。你只需描述整体造型，AI会设计服装、鞋履、发型和必要配饰；审核后生成套装图时，会以标准像为第一参考图完成换衣。</p><label>形象名称（可选）<input v-model="designForm.name" class="input" placeholder="例如：雨夜潜行造型"></label><label>新形象概念<textarea v-model="designForm.concept" class="textarea" rows="7" required placeholder="例如：为现代都市女记者设计雨夜调查形象，深灰防水风衣，便于行动但保持专业感，短发做湿发收束，低跟防滑短靴，只使用银色小耳钉，不要武器和剧情道具。"></textarea></label><label><input v-model="designForm.is_default" type="checkbox"> 设为默认套装</label><div class="field-hint">流程：标准像锁定身份 → AI拆分造型资产 → 人工审核 → 以标准像换衣生成完整套装图 → 生成四视图。不会修改或覆盖原标准像。</div><div class="actions"><button type="button" class="btn btn-ghost" @click="designing=false">取消</button><button class="btn" :disabled="designBusy||!designForm.concept.trim()">{{designBusy?'AI设计中…':'生成新形象草稿'}}</button></div></form></div>

    <div v-if="editingLook" class="modal-mask" @click.self="editingLook=null"><form class="modal card" @submit.prevent="saveLook"><h2>{{lookForm.id?'编辑':'新建'}}独立资产</h2><label>名称<input v-model="lookForm.name" class="input" required></label><label>分类<select v-model="lookForm.category" class="input"><option v-for="(v,k) in labels" :key="k" :value="k">{{v}}</option></select></label><label>描述<textarea v-model="lookForm.description" class="textarea" rows="5"></textarea></label><button type="button" class="btn btn-secondary" :disabled="expanding||!lookForm.name||!lookForm.description" @click="expandDraft">{{expanding?'AI扩写中…':'✨ AI扩写并生成提示词'}}</button><label>参考图提示词<textarea v-model="lookForm.prompt" class="textarea" rows="4"></textarea></label><label>优先级<input v-model.number="lookForm.priority" type="number" min="0" max="100" class="input"></label><div class="actions"><button type="button" class="btn btn-ghost" @click="editingLook=null">取消</button><button class="btn">保存</button></div></form></div>

    <div v-if="editingOutfit" class="modal-mask" @click.self="editingOutfit=null"><form class="modal card outfit-modal" @submit.prevent="saveOutfit"><h2>{{outfitForm.id?'编辑':'新建'}}完整套装</h2><label>套装名称<input v-model="outfitForm.name" class="input" placeholder="例如：日常工作造型" required></label><label>套装说明<textarea v-model="outfitForm.description" class="textarea" rows="3" placeholder="适用场景、整体气质"></textarea></label><label><input v-model="outfitForm.is_default" type="checkbox"> 设为默认套装</label><div v-for="(label,cat) in labels" :key="cat" class="asset-pick"><strong>{{label}}</strong><label v-for="x in looks.filter(v=>v.category===cat)" :key="x.id"><input v-model="outfitForm.look_ids" type="checkbox" :value="x.id"> {{x.name}} <small>({{x.audit_status}})</small></label><span v-if="!looks.some(v=>v.category===cat)" class="field-hint">暂无{{label}}资产</span></div><div class="actions"><button type="button" class="btn btn-ghost" @click="editingOutfit=null">取消</button><button class="btn">保存套装</button></div></form></div>
  </div>
</template>
<script setup>
import{computed,onMounted,onUnmounted,reactive,ref}from'vue';import{useRoute}from'vue-router';
const r=useRoute(),pid=r.params.id,cid=r.params.cid,character=ref(null),looks=ref([]),outfits=ref([]),motions=ref([]),mode=ref(['assets','outfits','motion'].includes(String(r.query.mode))?String(r.query.mode):'outfits'),activeCategory=ref('clothing'),editingLook=ref(null),editingOutfit=ref(null),designing=ref(false),designBusy=ref(false),error=ref(''),expanding=ref(false),motionName=ref(''),motionVideo=ref(null),motionAudio=ref(null),motionUploading=ref(false),lookForm=reactive({}),outfitForm=reactive({}),designForm=reactive({name:'',concept:'',is_default:false});let timer;
const labels={clothing:'服装',shoes:'鞋履',hair:'发型',hair_accessory:'发饰',jewelry:'首饰',bag:'包'};const filteredLooks=computed(()=>looks.value.filter(x=>x.category===activeCategory.value));const img=n=>`/api/input/${pid}/${n}`;const approved=o=>o.audit_status==='approved'||o.audit_status==='published';
async function request(url,opt={}){const res=await fetch(url,opt);if(!res.ok){let m='请求失败';try{m=(await res.json()).error||m}catch{}throw new Error(m)}return res.status===204?null:res.json()}
async function load(){try{const [characters,lookRows,outfitRows,motionRows]=await Promise.all([request(`/api/projects/${pid}/characters`),request(`/api/projects/${pid}/characters/${cid}/looks`),request(`/api/projects/${pid}/characters/${cid}/outfits`),request(`/api/projects/${pid}/characters/${cid}/motion-references`)]);character.value=(characters||[]).find(x=>String(x.id)===String(cid))||null;if(!character.value)throw new Error('当前角色不存在或不属于该项目');looks.value=lookRows;outfits.value=outfitRows;motions.value=motionRows}catch(e){error.value=e.message}}
function openDesign(){if(!character.value?.portrait){error.value='请先为当前角色生成或上传标准像';return}Object.assign(designForm,{name:'',concept:'',is_default:false});designing.value=true}
async function designOutfit(){designBusy.value=true;error.value='';try{await request(`/api/projects/${pid}/characters/${cid}/outfits/design`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(designForm)});designing.value=false;mode.value='outfits';await load()}catch(e){error.value=e.message}finally{designBusy.value=false}}
function openLook(x){Object.assign(lookForm,x||{id:0,name:'',category:'clothing',description:'',prompt:'',priority:50});editingLook.value=true}function derive(x){Object.assign(lookForm,{id:0,name:x.name+'变体',category:x.category,description:x.description,prompt:x.prompt,priority:x.priority});editingLook.value=true}
async function expandDraft(){expanding.value=true;try{const d=await request(`/api/projects/${pid}/characters/${cid}/looks/expand-preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lookForm)});lookForm.description=d.description;lookForm.prompt=d.prompt}catch(e){error.value=e.message}finally{expanding.value=false}}
async function saveLook(){const u=`/api/projects/${pid}/characters/${cid}/looks${lookForm.id?'/'+lookForm.id:''}`;await request(u,{method:lookForm.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(lookForm)});editingLook.value=null;load()}
async function actLook(x,a){try{await request(`/api/projects/${pid}/characters/${cid}/looks/${x.id}/${a}`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});load()}catch(e){error.value=e.message}}
async function upload(x,e){const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{await request(`/api/projects/${pid}/characters/${cid}/looks/${x.id}/image/upload`,{method:'POST',body:fd});load()}catch(er){error.value=er.message}}
async function removeLook(x){if(confirm(`删除资产“${x.name}”？`)){await request(`/api/projects/${pid}/characters/${cid}/looks/${x.id}`,{method:'DELETE'});load()}}
function openOutfit(o){Object.assign(outfitForm,{id:o?.id||0,name:o?.name||'',description:o?.description||'',is_default:!!o?.is_default,look_ids:o?.items?.map(i=>i.look_id)||[]});editingOutfit.value=true}
async function saveOutfit(){const u=`/api/projects/${pid}/characters/${cid}/outfits${outfitForm.id?'/'+outfitForm.id:''}`;await request(u,{method:outfitForm.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(outfitForm)});editingOutfit.value=null;load()}
async function outfitAct(o,a){try{await request(`/api/projects/${pid}/characters/${cid}/outfits/${o.id}/${a}`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});load()}catch(e){error.value=e.message}}
async function uploadOutfit(o,e,sheet){const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{await request(`/api/projects/${pid}/characters/${cid}/outfits/${o.id}/image/upload${sheet?'?kind=sheet':''}`,{method:'POST',body:fd});load()}catch(er){error.value=er.message}}
async function removeOutfit(o){if(confirm(`删除套装“${o.name}”？`)){await request(`/api/projects/${pid}/characters/${cid}/outfits/${o.id}`,{method:'DELETE'});load()}}
const fileURL=value=>{const p=String(value||'').replace(/\\/g,'/').replace(/^\/+/, '');const i=p.indexOf('/');return i>0?`/api/input/${p.slice(0,i)}/${p.slice(i+1)}`:`/api/input/${pid}/${p}`}
async function uploadMotion(){const video=motionVideo.value?.files?.[0];if(!video)return;motionUploading.value=true;const fd=new FormData();fd.append('video',video);const audio=motionAudio.value?.files?.[0];if(audio)fd.append('audio',audio);if(motionName.value)fd.append('name',motionName.value);try{await request(`/api/projects/${pid}/characters/${cid}/motion-references`,{method:'POST',body:fd});motionName.value='';motionVideo.value.value='';if(motionAudio.value)motionAudio.value.value='';await load()}catch(e){error.value=e.message}finally{motionUploading.value=false}}
async function selectMotion(m){try{await request(`/api/projects/${pid}/characters/${cid}/motion-references/${m.id}/select`,{method:'POST'});await load()}catch(e){error.value=e.message}}
async function deleteMotion(m){if(!confirm(`删除动态参考“${m.name}”？`))return;try{await request(`/api/projects/${pid}/characters/${cid}/motion-references/${m.id}`,{method:'DELETE'});await load()}catch(e){error.value=e.message}}
onMounted(async()=>{await load();if(r.query.design==='1')openDesign();else if(r.query.new==='1'&&mode.value==='assets')openLook();timer=setInterval(load,3000)});onUnmounted(()=>clearInterval(timer));
</script>
<style scoped>.head,.head-actions,.mode-tabs,.category-tabs,header,.actions,.chips{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.head{justify-content:space-between;margin:16px 0}.mode-tabs,.category-tabs{margin-bottom:16px}.look-grid,.outfit-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px}.look,.outfit{padding:16px}.look img,.empty-img,.outfit-media img{width:100%;height:210px;object-fit:contain;border-radius:10px;background:var(--bg-secondary);display:grid;place-items:center;color:var(--text-tertiary)}.outfit-binding{display:flex;align-items:center;gap:10px;margin-bottom:10px;padding:8px 10px;border-radius:9px;background:var(--accent-soft);font-size:11px;color:var(--text-secondary)}.outfit-binding img{width:44px;height:44px;border-radius:8px;object-fit:cover}.outfit-binding strong{color:var(--accent)}.outfit-media{display:grid;grid-template-columns:1fr 1fr;gap:8px}.outfit-media .empty-img{height:230px}header{justify-content:space-between}.chip{padding:4px 8px;border-radius:999px;background:var(--bg-secondary);font-size:12px}.error-text{color:var(--red);font-size:12px}.modal{width:min(680px,92vw);display:grid;gap:14px;padding:22px}.design-modal{width:min(720px,92vw)}.outfit-modal{max-height:90vh;overflow:auto}.character-anchor{display:flex;align-items:center;gap:14px;padding:14px 16px;margin-bottom:12px}.character-anchor img,.anchor-empty{width:72px;height:72px;border-radius:12px;object-fit:cover;background:var(--bg-secondary)}.anchor-empty{display:grid;place-items:center;font-size:11px;color:var(--text-tertiary)}.character-anchor>div:last-child{display:grid;gap:5px}.character-anchor span{font-size:12px;color:var(--text-secondary)}.workflow-tip{display:flex;gap:10px;align-items:center;flex-wrap:wrap;padding:12px 16px;margin-bottom:16px;font-size:12px;color:var(--text-secondary)}.workflow-tip strong{color:var(--accent)}.modal label,.asset-pick{display:grid;gap:6px}.asset-pick{padding:10px;border:1px solid var(--border);border-radius:10px}.motion-panel{padding:18px}.motion-upload{display:grid;grid-template-columns:1fr 1fr 1fr auto;gap:12px;align-items:end}.motion-upload label{display:grid;gap:6px}.motion-row{display:grid;grid-template-columns:180px 1fr auto auto;gap:12px;align-items:center;padding:12px 0;border-top:1px solid var(--border)}.motion-row video{width:180px;max-height:120px;background:#000;border-radius:8px}@media(max-width:760px){.motion-upload,.motion-row{grid-template-columns:1fr}.motion-row video{width:100%}}</style>
