<template><div class="page fade-up"><div class="head-links"><router-link :to="`/projects/${id}/novel`" class="back">← 小说章节</router-link></div><div class="page-head"><div><h1>故事圣经</h1><p class="sub">先生成有内容的基础草稿，再逐项检查并审核；后续窗口通过增量建议更新。</p></div><div class="actions"><span v-if="bible" class="badge">{{ bible.status }} · v{{bible.version}}</span><button v-if="bible && bible.status!=='approved'" class="btn btn-secondary" :disabled="busy" @click="generate">{{busy?'生成中…':'重新生成基础草稿'}}</button><button class="btn" :disabled="busy || !reviewable" :title="reviewable?'':'草稿为空或内容不完整，不能审核'" @click="approve">审核通过</button><router-link v-if="bible?.status === 'approved'" :to="`/projects/${id}/adaptation`" class="btn">分集规划 →</router-link></div></div><div v-if="error" class="card error">{{ error }}</div><div v-if="!bible" class="card empty"><h2>还没有可审核的故事圣经</h2><p>请先确保当前窗口已经生成故事弧，然后生成基础草稿。生成成功后，核心前提、世界规则、主线、关系和伏笔等内容会显示在下方。</p><button class="btn" :disabled="busy" @click="generate">{{busy?'正在生成故事圣经…':'生成基础故事圣经'}}</button><router-link :to="`/projects/${id}/novel`" class="btn btn-ghost">返回检查故事弧</router-link></div><div v-else-if="!complete" class="card incomplete"><strong>当前草稿内容不完整，不能审核</strong><span>至少需要核心前提、世界规则和主线。请重新生成或手工补全并保存。</span></div><section v-if="changes.length" class="card changes"><h2>待审核增量建议</h2><article v-for="change in changes" :key="change.id"><header><strong>基于Story Bible v{{change.base_version}}</strong><span class="badge">{{change.status}}</span></header><pre>{{pretty(change.candidate_json)}}</pre><div v-if="change.status==='pending'" class="actions"><button class="btn btn-sm" :disabled="busy" @click="reviewChange(change,true)">审核并合并</button><button class="btn btn-sm btn-ghost" :disabled="busy" @click="reviewChange(change,false)">拒绝</button></div></article></section><form v-if="bible" class="card form" @submit.prevent="save"><label>核心前提<textarea v-model="form.premise" class="textarea" rows="4"/></label><label v-for="f in fields" :key="f.key">{{ f.label }}<textarea v-model="form[f.key]" class="textarea" rows="7"/></label><button class="btn" :disabled="busy">保存为待审核草稿</button></form></div></template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue';import { useRoute } from 'vue-router';import { api } from '../api'
const id=useRoute().params.id,bible=ref(null),changes=ref([]),busy=ref(false),error=ref(''),form=reactive({});const fields=[['world_rules','世界规则'],['main_plot','主线'],['subplots','支线'],['timeline_json','时间线'],['relationships_json','人物关系'],['clue_ledger_json','伏笔台账'],['location_bible_json','地点'],['prop_bible_json','道具']].map(([key,label])=>({key,label}))
const complete=computed(()=>!!(String(form.premise||'').trim()&&validValue(form.world_rules)&&validValue(form.main_plot)))
const reviewable=computed(()=>bible.value?.status==='draft'&&complete.value)
function validValue(value){const text=String(value||'').trim();return !!text&&text!=='null'&&text!=='{}'&&text!=='[]'}
function apply(v){bible.value=v;Object.assign(form,v)}function pretty(raw){try{return JSON.stringify(JSON.parse(raw),null,2)}catch{return raw}}
async function load(){try{apply((await api.storyBible(id)).data)}catch(e){if(e.response?.status!==404)error.value=e.response?.data?.error||e.message}try{changes.value=(await api.storyBibleChanges(id)).data.changes||[]}catch{changes.value=[]}}
async function generate(){if(bible.value?.status==='approved'){error.value='已审核的Story Bible不能直接覆盖，请在小说窗口完成故事弧后生成增量建议。';return}busy.value=true;error.value='';try{apply((await api.generateStoryBible(id)).data.story_bible)}catch(e){error.value=e.response?.data?.error||e.message}finally{busy.value=false}}
async function save(){busy.value=true;try{const data={premise:form.premise};for(const f of fields)data[f.key]=form[f.key]||'';apply((await api.updateStoryBible(id,data)).data)}catch(e){error.value=e.response?.data?.error||e.message}finally{busy.value=false}}
async function approve(){busy.value=true;try{apply((await api.approveStoryBible(id)).data)}catch(e){error.value=e.response?.data?.error||e.message}finally{busy.value=false}}
async function reviewChange(change,approveChange){const note=window.prompt(approveChange?'合并说明（可选）':'拒绝原因','');if(note===null)return;busy.value=true;try{apply((await api.reviewStoryBibleChange(id,change.id,approveChange,note)).data);await load()}catch(e){error.value=e.response?.data?.error||e.message}finally{busy.value=false}}
onMounted(load)
</script><style scoped>.page-head,.changes article header{display:flex;justify-content:space-between;gap:16px;margin-bottom:18px}.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.form,.changes{padding:22px;display:grid;gap:18px}.form label{display:grid;gap:8px;font-weight:600}.changes article{border:1px solid var(--border);border-radius:10px;padding:14px}.changes pre{max-height:300px;overflow:auto;white-space:pre-wrap}.empty,.error,.incomplete{padding:30px}.empty h2{margin-top:0}.empty p{max-width:720px;color:var(--text-secondary);line-height:1.7}.empty .btn{margin-right:10px}.incomplete{display:grid;gap:7px;border-color:#f59e0b88;color:#f59e0b}.error{color:var(--red)}@media(max-width:700px){.page-head{display:block}.actions{margin-top:12px}}</style>
